site_title = "MyArxiv"
limit_days = 7
cache_url = "https://minie135.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.AR"
title = "Hardware Architecture"

[[sources]]
limit = 150
category = "cs.CR"
title = "Cryptography and Security"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MA"
title = "Multiagent Systems"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
